#! /bin/bash
alias ll='ls -AhlF --color=auto'
alias la='ls -Ah'
alias l='ls -CFh'
alias l.='ls -d .* --color=tty'         # short listing, only hidden files - .*
alias ltime='ls -lAthF'                 # long, sort by newest to oldest
alias Ltime='ls -lAtrhF'                # long, sort by oldest to newest
alias lchange='ls -lcr'                 # sort by change time
alias lh='ls -lSrh'                     # sort by size human readable
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias cp='cp -v'
alias mv='mv -iv'
alias mkdir='mkdir -pv'
alias path='echo -e ${PATH//:/\\n}'     # path:  Echo all executable Paths
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias c-='cd -'

alias cdbase='conda activate base'
alias cddeact='conda deactivate'
alias jl='jupyter lab --no-browser'
alias root='root -l'

alias bap='bat -P'

alias lxplus='ssh lxplus'
alias psi='ssh psi'
alias ihep='ssh ihep'
alias uzh='ssh uzh'

alias cmsevn='cmsenv'
alias cmsnev='cmsenv'
alias csmenv='cmsenv'
alias cmesnv='cmsenv'


# slurm aliases
alias sq='squeue -u $USER'
alias sqall='squeue -u $USER -all'

spy() { squeue | tail -n +2 | awk '{if($5=="R"){r[$4]++}else if(match($1,/_\[([0-9]+)-([0-9]+)\]/,a)){d=a[2]-a[1];j[$4]+=d;T+=d} j[$4]++; T++} END {for(n in j){if(r[n]==""){r[n]=0} printf "%7s / %-5s - %s\n",r[n],j[n],n } printf "%7s\n",T}'; }

sqs() {squeue -o '  %16i %80j %3t %9u %.8M %.1D %20R %4P' -u ${USER} | grep "$1" | tail -n +2 | awk '{ if($3=="R"){r[$2]++;R++}else if(match($1,/_\[([0-9]+)-([0-9]+)\]/,a)){D=a[2]-a[1];t[$2]+=D;T+=D} t[$2]++; T++ sub(/_.+/,"",$1); d[$2][$1]++; } END {for(i in t){ printf "%5d/%-5d %-45s",r[i],t[i],i; for(j in d[i]){ printf " %s",j }; printf "\n" }; printf "%5d/%-5d",R,T};' | sort -n | grep "$1";}

init-voms-proxy() {echo $VOMSUSERPASS | voms-proxy-init -voms cms -valid 192:00; }